export const Types = {
  PHOTOS_FETCH_REQUEST: 'PHOTOS_FETCH_REQUEST', 
  PHOTOS_SET_PAGE_AND_REQUEST_FETCH: 'PHOTOS_SET_PAGE_AND_REQUEST_FETCH', 
  PHOTOS_FETCH_REQUEST_PAGE: 'PHOTOS_FETCH_REQUEST_PAGE', 
  PHOTOS_FETCH_SUCCESS: 'PHOTOS_FETCH_SUCCESS', 
  PHOTOS_FETCH_FAILURE: 'PHOTOS_FETCH_FAILURE', 
}