export const Types = {
  PHOTOS_FETCH_REQUEST_PAGE: 'PHOTOS_FETCH_REQUEST_PAGE', 
  PHOTOS_FETCH_PAGE_SUCCESS: 'PHOTOS_FETCH_PAGE_SUCCESS', 
  PHOTOS_FETCH_PAGE_FAILURE: 'PHOTOS_FETCH_PAGE_FAILURE', 
}